import logo from './logo.svg';
import './App.css';
import React from "react";
import { Unity, useUnityContext } from "react-unity-webgl";

function App() {
  const { unityProvider } = useUnityContext({
    loaderUrl: "Build/unityTest.loader.js",
    dataUrl: "Build/unityTest.data.unityweb",
    frameworkUrl: "Build/unityTest.framework.js.unityweb",
    codeUrl: "Build/unityTest.wasm.unityweb",
  });

  //comment out below line if you want to use the index.html file generated by unity and rename the unity_index.html to index.html
  //and change reacts index.html file to something else 
  return <Unity unityProvider={unityProvider} style={{ width: 1800, height: 1300 }} />;
}

export default App;
